models/Containers.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "containers".
 *
 * @property int $id
 * @property string $buking
 * @property string $reliz
 * @property string $stock
 * @property string $number
 * @property string $type
 * @property string $date_in
 * @property string $time_in
 * @property string $date_out
 * @property string $date_repair
 * @property string $am_number
 * @property string $am2
 * @property int $conditions
 * @property int $status
 * @property int $block
 * @property string $note
 * @property int $operation
 * @property string $time_out
 * @property int $am_id
 */
class Containers extends LogModel
{

    public $cnt;
    public $price;

    public static function tableName()
    {
        return 'containers';
    }

    public function rules()
    {
        return [
            [['stock', 'number', 'type', 'date_in', 'am_number', 'conditions', 'status', 'block'], 'required'],
            [['am_number','am2','operation','am_id','reliz','date_in', 'date_out', 'date_repair', 'time_out','cnt'], 'safe'],
            [['note'], 'string'],

        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'buking' => 'Букинг',
            'reliz' => 'Релиз',
            'stock' => 'Сток',
            'number' => 'Номер конт-ра',
            'type' => 'Тип',
            'date_in' => 'Дата прихода ',
            'time_in' => 'Время прихода',
            'date_out' => 'Дата выдачи',
            'date_repair' => 'Дата ремонта',
            'am_number' => 'Номер АМ',
            'am2' => 'АМ Комп.',
            'conditions' => 'Состояние конт-ра',
            'status' => 'Порожний/ Груженый',
            'block' => 'Блок',
            'note' => 'Примечание',
            'operation' => 'Операции',
            'time_out' => 'Time Out',
            'am_id' => 'Am ID',
            'condText'=>'Состояние',
            'statusText'=>'Статус',
            'blockText'=>'Блок',
            'price'=>'Итого',
            'calc_error_code' => 'Смета'
        ];
    }

    public function beforeSave($insert)
    {
        Yii::$app->cache->flush();
        if (parent::beforeSave($insert)) 
        {
            return true;
        } else {
            return true;
        }
    }

    public function afterDelete()
    {
        Yii::$app->cache->flush();
        parent::afterDelete();
    }

    public function getStock_r()
    {
        return $this->hasOne(Stock::className(), ['id' => 'stock']);
    }

    public function getType_r()
    {
        return $this->hasOne(Types::className(), ['id' => 'type']);
    }

    public function getReliz_r()
    {
        return $this->hasOne(Reliz::className(), ['number' => 'reliz']);
    }

    public static function getStatusArr()
    {
        return [
            'Порожний',
            'Груженный'
        ];
    }

    public function getPrice()
    {
        return 'Итого';
    }

    public function getStatusText()
    {
        $items = Containers::getStatusArr();
        return isset($items[$this->status]) ? $items[$this->status] : '';
    }

    public static function getCondArr()
    {
        return [
            'Исправен',
            'Грязный',
            'Поврежден'
        ];
    }

    public function getCondId($name)
    {
        $items = Containers::getCondArr();
        foreach ($items as $i => $item)
        {
            if ($item === trim($name))
                return $i;
        }
        return 0;
    }

    public function getCondText()
    {
        $items = Containers::getCondArr();
        return isset($items[$this->conditions]) ? $items[$this->conditions] : '';
    }    

    public static function getBlockArr()
    {
        return ['Нет','Да'];
    }

    public function getBlockText()
    {
        $items = Containers::getBlockArr();
        return isset($items[$this->block]) ? $items[$this->block] : '';
    }

    public function getStockId($name)
    {
        $stocks = Stock::find()->all();
        if ($stocks === null || !is_array($stocks))
            return 0;
        foreach ($stocks as $stock)
        {
            if ($stock->name === $name)
                return $stock->id;
        }
        return 0;
    }

    public static function getCountByStocks()
    {
        $list = Containers::find()
            ->select(['COUNT(*) AS cnt','stock'])
            ->groupBy(['stock'])
            ->orderBy('cnt DESC')
            ->all();
        return $list === null ? [] : $list;
    }

    public function getCalc()
    {
        return $this->hasOne(Calc::className(), ['container_id' => 'id'])->orderBy('id DESC');
    }

}

models/Contracts.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "contracts".
 *
 * @property int $id
 * @property string $org
 * @property string $container_type
 * @property string $container_size
 * @property string $location
 * @property string $element
 * @property string $repair_type
 * @property string $repair_code
 * @property string $repair_desc
 * @property string $price
 * @property double $hours
 * @property int $max_count
 * @property string $loc_code
 */
class Contracts extends \yii\db\ActiveRecord
{

    const REPAIR_CODE   = '0003';
    const PREPARE_CODE  = '0917';

    public static function tableName()
    {
        return 'contracts';
    }

    public function rules()
    {
        return [
            [['org', 'container_type', 'container_size', 'location', 'element', 'repair_type', 'repair_code', 'repair_desc', 'price', 'hours', 'max_count', 'loc_code'], 'required'],
            [['max_count'], 'integer'],
            [['price', 'hours'], 'number'],
            [['org', 'container_type', 'container_size', 'location', 'element', 'repair_type', 'repair_code', 'repair_desc', 'loc_code'], 'string', 'max' => 255],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'org' => 'Организация',
            'container_type' => 'Тип',
            'container_size' => 'Размер',
            'location' => 'Расположение',
            'element' => 'Элемент',
            'repair_type' => 'Вид ремонта',
            'repair_code' => 'Код',
            'repair_desc' => 'Описание ремонта',
            'price' => 'Стоимость',
            'hours' => 'Нормочасы',
            'max_count' => 'Количество',
            'loc_code' => 'Loc Code',
        ];
    }

    public function beforeSave($insert)
    {
        Yii::$app->cache->flush();
        if (parent::beforeSave($insert)) 
        {
            return true;
        } else {
            return true;
        }
    }

    public function afterDelete()
    {
        Yii::$app->cache->flush();
        parent::afterDelete();
    }

    public function getOrg_r()
    {
        return $this->hasOne(Orgs::className(), ['id' => 'org']);
    }

    public static function getOrg_id($name)
    {

        $org = Orgs::find()->where(['name' => $name])->one();
        return $org != null? $org->id : 0;
    }

    public static function getLocations($org_id, $container_size)
    {  
        // var_dump($org_id ,$container_size);exit;
        $records = Contracts::find()
            ->where(['org' => $org_id, 'container_size' => $container_size])
            ->groupBy(['location'])
            ->all();
        return $records ? $records : [];
    }

    public static function getElements($location, $container_size)
    {
        $records = Contracts::find()
            ->where(['location' => $location, 'container_size' => $container_size])
            ->groupBy(['element'])
            ->all();
        return $records ? $records : [];
    }

    public static function getTypes($element, $container_size,$location='')
    {
		if ($location!='') {
			$records = Contracts::find()
            ->where(['element' => $element, 'container_size' => $container_size,'location'=>$location])
            ->groupBy(['repair_type'])
            ->all();
		} else {
			$records = Contracts::find()
            ->where(['element' => $element, 'container_size' => $container_size])
            ->groupBy(['repair_type'])
            ->all();
        }    
        return $records ? $records : [];
    }

    public static function getByCode($repair_code, $container_size)
    {
        $records = Contracts::find()
            ->where(['repair_code' => $repair_code, 'container_size' => $container_size])
            ->groupBy(['repair_type'])
            ->one();
        return $records ? $records : [];
    }
    
    public static function getByRepair($repair_code)
    {
        $records = Contracts::find()
            ->where(['repair_code' => $repair_code])
            ->groupBy(['repair_type'])
            ->one();
        return $records ? $records : [];
    }

}

models/Reliz.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "reliz".
 *
 * @property int $id
 * @property string $stock
 * @property string $type_cnt
 * @property int $amount
 * @property int $rest
 * @property string $date
 * @property string $date_to
 * @property string $number
 * @property string $buking
 * @property int $method
 * @property int $type
 * @property int $status
 * @property string $comment
 */
class Reliz extends LogModel
{
    public $sum;

    public static function tableName()
    {
        return 'reliz';
    }

    public function rules()
    {
        return [
            [['stock', 'type_cnt', 'amount', 'date', 'number', 'buking', 'method'], 'required'],
            [['amount', 'rest', 'method', 'type', 'status'], 'integer'],
            [['date', 'date_to', 'sum'], 'safe'],
            [['comment'], 'string'],
            [['stock', 'type_cnt', 'number', 'buking'], 'string', 'max' => 255],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'stock' => 'Сток',
            'type_cnt' => 'Тип',
            'amount' => 'Кол-во',
            'rest' => 'Остаток',
            'restCount' => 'Остаток',
            'date' => 'Дата выдачи',
            'date_to' => 'Дата выгрузки по',
            'formated_dates' => 'Дата выдачи',
            'number' => 'Релиз',
            'buking' => 'Букинг',
            'method' => 'Способ отгрузки',
            'type' => 'Тип',
            'status' => 'Статус',
            'comment' => 'Комментарий',
            'countByReliz' => 'Остаток конт.'
        ];
    }

    public function beforeSave($insert)
    {
        Yii::$app->cache->flush();
        if (parent::beforeSave($insert)) 
        {
            return true;
        } else {
            return true;
        }
    }

    public function afterDelete()
    {
        Yii::$app->cache->flush();
        parent::afterDelete();
    }

    public function getLabel($attribute)
    {
        $labels = $this->attributeLabels();
        return isset($labels[$attribute]) ? $labels[$attribute] : '';
    }

    public function getContType()
    {
        return $this->hasOne(Types::className(), ['name' => 'type_cnt']);
    }

    public function getStock_r()
    {
        return $this->hasOne(Stock::className(), ['name' => 'stock']);
    }

    public function getAutos()
    {
        return $this->hasMany(Autos::className(), ['reliz_id' => 'id']);
    }

    public function getContainers()
    {
        return $this->hasMany(Containers::className(), ['reliz' => 'number']);
    }

    public function getFormatedDates()
    {
        return $this->date . ' / ' . $this->date_to;
    }

    public static function getTypeArr()
    {
        return [
            'Простой',
            'Номерной'
        ];
    }

    public function getTypeText()
    {
        $items = Reliz::getTypeArr();
        return isset($items[$this->type]) ? $items[$this->type] : '';
    }

    public static function getMethodArr()
    {
        return [
            'Затарка',
            'Выдача на АМ'
        ];
    }

    public function getMethodText()
    {
        $items = Reliz::getMethodArr();
        return isset($items[$this->method]) ? $items[$this->method] : '';
    }

    public static function getStatusArr()
    {
        return ['Не исполнен','Активный'];
    }

    public function getStatusText()
    {
        $items = Reliz::getStatusArr();
        return isset($items[$this->status]) ? $items[$this->status] : '';
    }

    public function getLogText()
    {
        return '';
    }

    public function getReceptionDate()
    {
        return $this->date . '/' . $this->date_to;
    }

    public function getCountByReliz()
    {
        $c = Containers::find()
            ->select(['COUNT(*) AS cnt', 'reliz'])
            ->where( [ 'reliz'=> $this->number ] )
            ->one();
        return $c === null ? 0 : $c->cnt;
    }

    public function getRestCount()
    {
        return $this->amount - $this->getCountByReliz();
    }
}

controllers/ContractsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Users;
use app\models\Calc;
use app\models\CalcSearch;
use app\models\Contracts;
use app\models\ContractsSearch;
use app\models\Containers;


class ContractsController extends ConfigBaseController
{

    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //         'access' => [
    //             'class' => AccessControl::className(),
    //             'only' => ['index', 'info', 'view', 'create', 'update', 'delete'],
    //             'rules' => [ 
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['index', 'info', 'view', 'create', 'update', 'delete'],
    //                     'roles' => [ Users::ROLE_ADMIN ],
    //                 ] 
    //             ],
    //         ],
    //     ];
    // }
    public function actionIndex($org = null)
    {   
        if ($org == null) {
            return $this->render('index', [
                'dataProvider' => false,
                'org' => isset($org) ? $org : 1 
            ]);
        }
        $searchModel = new ContractsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['org' => $org]);
        $sort = $dataProvider->getSort();
        $sort->defaultOrder = ['id' => SORT_DESC];
        $dataProvider->setSort($sort);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'org' => isset($org) ? $org : 1 
        ]);
    }

    public function actionInfo($id)
    {
        $container = Containers::find()->where(['id' => $id])->one();
        if($container === null)
            return $this->redirect(['containers/index']);

        $contract = Calc::find()->where( ['container_id' => $id ] )->orderBy('id DESC')->one();
        require('/home/sys78/cntdepot.ru/docs/inc/phpQuery.php');
        $contract->html = \phpQuery::newDocument(stripslashes(htmlspecialchars_decode($contract->html)));
        foreach ($contract->html->find('tr') as $tr) {
            if (pq($tr)->attr('class') != '') continue;
            $allPrice = pq($tr)->find('td')->eq(7)->html();
            $allPrice = round($allPrice, 2);
            $allPrice = pq($tr)->find('td')->eq(7)->html($allPrice);
        }
        if($contract === null)
            return $this->redirect(['containers/index']);

        return $this->render('info', [
            'container' => $container,
            'contract'  => $contract
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Contracts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) 
        {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) 
        {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $calc = Calc::findOne( ['id'=>$id] );
        if ($calc !== null)
        {
            $container = Containers::findOne([ 'id' => $calc->container_id ]);
            $container->date_repair = null;
            $container->save();
            $calc->delete();
        }

        return $this->redirect(['containers/index']);
    }

    protected function findModel($id)
    {
        if (($model = Contracts::findOne($id)) !== null) 
        {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/contracts/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Orgs;
use app\models\Hoursprice;
?>

<div class="contracts-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'org')->dropDownList(Orgs::getOrgNames()) ?>

    <?= $form->field($model, 'container_size')->dropDownList(Hoursprice::getContainerSize()) ?>

    <?= $form->field($model, 'container_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'location')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'element')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'repair_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'repair_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'repair_desc')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hours')->textInput() ?>

    <?= $form->field($model, 'max_count')->textInput() ?>

    <?= $form->field($model, 'loc_code')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/contracts/create.php
<?php

use yii\helpers\Html;

$this->title = 'Добавить контракт';
$this->params['breadcrumbs'][] = ['label' => 'Контракты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contracts-create">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/contracts/index.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use app\models\Orgs;
use app\models\Contracts;

$this->title = 'Контракты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contracts-index">

    <h3><?= Html::encode($this->title) ?></h3>

    <p>
        <?= Html::a('Фильтр', ['#'], ['class' => 'btn btn-success','onclick' => '$( ".filters" ).toggle();return false;']) ?>
        <?= Html::a('Добавить вид работ', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p>
        <?php
            $model = new Contracts;
            $model->org = $org;

            $form = ActiveForm::begin(['action'=> '', 'method' => 'get']); 

            echo $form->field($model, 'org')->dropDownList(Orgs::getOrgs());
        ?>

            <div class="form-group">
                <?= Html::submitButton('Выбрать', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
    </p>

    <?php 
    
    if ($dataProvider !== false) :

        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'summary' => false,
            'columns' => [
                'id',
                [
                    'attribute'=>'org_r.name',
                    'filter'=>ArrayHelper::map(Orgs::find()->asArray()->all(), 'name', 'name'),
                ],
                'container_type',
                'container_size',
                'location',
                'element',
                'repair_type',
                'repair_code',
                'repair_desc',
                'price',
                'hours',
                'max_count',
                'loc_code',
                [
                    'class' => 'yii\grid\ActionColumn',
                ],
            ],
        ]); 
    ?>
    <?php else: ?>
        <p>Нет данных</p>
    <?php endif;?>
</div>
<script>
    $('#contracts-org').attr('name','org');
</script>

views/contracts/info.php
<?php

use yii\helpers\Html;

?>
<div id="container-info">
	<table class="table table-striped table-bordered">
		<tr>
			<td>Номер</td>
			<td><?= $container->number ?></td>
		</tr>
		<tr>
			<td>Тип</td>
			<td><?= $container->type_r->name ?></td>
		</tr>
		<tr>
			<td>Размер</td>
			<td><?= $container->type_r->type ?></td>
		</tr>
		<tr>
			<td>Сток</td>
			<td><?= $container->stock_r->name ?></td>
		</tr>
		<tr>
			<td>Дата приема</td>
			<td><?= $container->date_in ?></td>
		</tr>
		<tr>
			<td colspan="2"><?= $container->note ?></td>
		</tr>
	</table>
</div>

<div>
	<p class="text-danger">
		<?php
			if ($contract->error_code == 0) {
				echo "Нет ответа клиента</p>";
				echo Html::a('Редактировать смету', ['containers/contracts','id' => $container->id ], ['class' => 'btn btn-success']);
			}
			if ($contract->error_code == 1) {
				echo "Смета обработана</p>";
				if (Yii::$app->user->can('repairButton')) {
					echo Html::a('Редактировать смету', ['containers/contracts','id' => $container->id ], ['class' => 'btn btn-success']);
				}
			}
			if ($contract->error_code == 2) {
				echo $contract->error_text.'</p>';?>
				<!-- <a href="" class="btn btn-success">Редактировать смету</a> -->
				<?= Html::a('Редактировать смету', ['containers/contracts','id' => $container->id ], ['class' => 'btn btn-success']) ?>
				<?php 
			}
		?>
	

</div>

<div id="contract-info">
	<h5>Результат от: <?= $contract->date_add ?> (
	<?php if($container->status != 2): 
		echo Html::a(
            'Удалить',
            ['delete', 'id' => $contract->id],
            [
            	'data' => [
            	    'confirm' => 'Удалить запись?',
	            	'method' => 'post',
        		],
        	]
        ); 
	endif;
        ?> )</h5>
	<?= stripslashes(htmlspecialchars_decode($contract->html)); ?>
</div>

views/contracts/update.php
<?php

use yii\helpers\Html;

$this->title = 'Редактировать контракт';
$this->params['breadcrumbs'][] = ['label' => 'Контракты', 'url' => ['index']];

?>
<div class="contracts-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/contracts/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title =  'Контракты';
$this->params['breadcrumbs'][] = ['label' => 'Контракты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="contracts-view">

    <h3><?= Html::encode($this->title) ?></h3>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Действительно удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'org',
            'container_type',
            'container_size',
            'location',
            'element',
            'repair_type',
            'repair_code',
            'repair_desc',
            'price',
            'hours',
            'max_count',
            'loc_code',
        ],
    ]) ?>

</div>